theme: jekyll-theme-minimal
title: Causal Incentives Working Group
description: We are a collection of researchers, interested in using causal models to understand the incentives of AI systems. We are particularly interested in applying these models to the design of safe and fair AI algorithms. If you are interested in working on these problems, as a collaborator, visitor, or in any other capacity feel free to reach out to us.

logo: logo.png
